### ISSUE TITLE
[BUG] Wrong behaviour in site configuration module ?

### ISSUE THREAD

**Issue by wtfred** [pixelant/pxa_lpeh#10]
Hello there,

If i'm not mistaken, the behaviour with extension configuration and site configuration module is reversed:

When "Don't replace the standard 'Show Content from Page' error handler" is checked, and we select "Php Class" in "errorHandler", we only have access to the field "ErrorHandler Class Target (FQCN)" and not "errorContentSource"

When the box is unchecked, and we select "Php Class" in "errorHandler", we have access to both field

So by using only the site configuration module, and not manually editing config.yaml, we cannot do what you are describing in https://github.com/pixelant/pxa_lpeh#disabling-page-content-error-handler-override

**Comment by MattiasNilsson** [comment]
@wtfred For which version of TYPO3 do you have this error? If you are using TYPO3 11 this feature is already built in:

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.html#featureflag-subrequestpageerrors

https://github.com/t3kit/t3kit-starter/blob/f9a0c7cbf7c57973d3cabcd7e82ce6155116bc99/public/typo3conf/LocalConfiguration.php#L134

**Comment by wtfred** [comment]
@MattiasNilsson I'm using TYPO3 10.4.22 at the moment, but it's good to now this made his way to the core for TYPO3 11 :)
