### ISSUE TITLE
[TASK] Using "cache_" prefix is deprecated in TYPO3v10

### ISSUE THREAD

**Issue by cweiske** [pixelant/pxa_lpeh#13]
pxa_lpeh uses CacheManager to fetch cache instances in `LocalPageErrorHandler::buildDispatcher()`: https://github.com/pixelant/pxa_lpeh/blob/358bd570d829d22bac9b4d7293105176cd59f927/Classes/Error/PageErrorHandler/LocalPageErrorHandler.php#L118

In TYPO3 v10, the "cache_" prefix for all the cache names has been removed. Calling `CacheManager::getCache('cache_runtime')` is deprecated since then: https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Deprecation-88366-DefaultCachingFrameworkCacheNamesChanged.html

Using it generates deprecation notices:
> TYPO3 Deprecation Notice: Accessing a cache with the "cache_" prefix as in "cache_runtime" is not necessary anymore, and should be called without the cache prefix. in /var/www/site/htdocs/typo3/sysext/core/Classes/Cache/CacheManager.php line 151

With TYPO3 v12, the fallback will be removed.

How can this be solved, given that the extension supports TYPO3 9?
Core version specific code?

(Related: https://github.com/FluidTYPO3/flux/issues/1953)

**Comment by mabolek** [comment]
Hi @cweiske! Thank you for reporting this.

The functionality of the extension has been included in TYPO3 core from v11, so we should only need to include a fix that removes the deprecation message for v10. A simple condition that omits the "cache_" prefix.

**Comment by cweiske** [comment]
This report is an error.
pxa_lpeh already executes different code for typo3v10 :(
